### PR TITLE
Update README.md to include better Python dependencies installation command

### PR DESCRIPTION
**Pull request by DaleMitchell**
When I attempted to run the command as is, my console gave all of these nasty error messages:

Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 380, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError

This error was resolved by running the command I have included in this commit.

### CODE REVIEW

**Comment by anishathalye** [comment]
This seems like a bug in pip or an issue with your installation?

Pip includes a cache for a reason, and it's on by default, so the developers expect it to work: https://pip.pypa.io/en/stable/reference/pip_install/#caching

**Comment by DaleMitchell** [comment]
It is a common issue with pip and is not exclusive to my installation.

https://github.com/pypa/pip/issues/2984

Unless a user is frequently reinstalling packages (such as a developer with a mainstream laptop who is working on more than several different and sophisticated Python projects), caching is not necessary and for most servers is often a problem. As you may already know, servers are generally configured to have only as many resources as they really need, as servers with more RAM and storage are more costly. For this reason, we should recommend that people disable it. Otherwise, many users will become perplexed and spend time searching for a workaround. This can be prevented by including my suggestion of editing this project's readme.

https://stackoverflow.com/questions/29466663/memory-error-while-using-pip-install-matplotlib
https://stackoverflow.com/questions/39408409/unable-to-upgrade-scipy-using-pip
https://stackoverflow.com/questions/44335087/unable-to-install-tensorflow-memoryerror
https://stackoverflow.com/questions/19595944/trouble-installing-scipy-in-virtualenv-on-a-amazon-ec2-linux-micro-instance/20890162
https://stackoverflow.com/questions/32892468/encoding-error-when-attempt-to-install-matplotlib-on-ubuntu

**Comment by anishathalye** [comment]
Ok, makes sense. Thanks for explaining it to me!

Merged.

**Comment by DaleMitchell** [comment]
Awesome! I'll definitely let you know if I find any other possible improvements.

Off topic of this pull request: It is possible that I'll convince my university's hackathon/makeathon program to adopt (or adapt, either word might be correct although I haven't been corrected yet lol) your project. In the past, we have used a cluttered combination of Qualtrics surveys or Google forms, spreadsheets, etc. If this web app turns out to be of great use for streamlining the judging process of our events, we will be grateful for all of the hard work put into this project of yours, and we'll definitely give credit where credit is due, just like what we're doing with Quill: https://github.com/ElectronicsOSU/quill-MakeOHIO-2018

Thank you! 😄

**Comment by anishathalye** [comment]
Yeah, please let me know if you find anything else that can be improved.

Ooh, that'll be cool. Glad to hear that you're considering using Gavel :)

**Pull request merged**
