### PR TITLE
Import judge and project data through file uploads

### PR DESCRIPTION
**Pull request by rjchee**
This PR should handle #52

### CODE REVIEW

**Comment by anishathalye** [comment]
Awesome, this is a much-needed change! Thanks so much for the submission @rjchee / @copperstick6.

From a quick glance, the patch looks good. I should be able to look it over in detail early this weekend.

**Comment by anishathalye** [comment]
Oh, one thing I just noticed -- could you rebase/squash into a single commit? We don't need to keep the intermediate work.

**Comment by rjchee** [comment]
Squashed :+1:

**Comment by anishathalye** [comment]
Looks awesome! I merged 23625195351aa26bf660b4f3c5014ed1b2963f0e in 38ba27a7b3c3bd5d6881f632d11421d52510a0cf and added some basic data validation in d841d808b29e146b806f201ef75a240983202753.

This is currently in `develop`. We'll fast-forward `master` soon.

**Pull request closed without merging**
