### PR TITLE
Added Heroku button

### PR DESCRIPTION
**Pull request by phoenix1796**
Changelog:

Files Added : 
- Procfile
- app.json

Files Updated:
- README.md
- gavel.py
    - Added Host and port params to app.run
    - Added DATABASE_URL environment variable for SQL_ALCHEMY DB URI

### CODE REVIEW

**Comment by anishathalye** [comment]
Will squash and merge this, probably tonight.

**Comment by anishathalye** [comment]
Looks okay to me, but I don't have that much experience with Heroku.

@manojpandey, wanna take a look at this before I merge it?

**Comment by manojpandey** [comment]
@anishathalye LGTM. Squash and merge.

**Comment by anishathalye** [comment]
Wow, that was a quick response.

Merged in c55073266180210d43978303424c3adcfc8ffb9d!

Btw, @phoenix1796, lmk if it's okay to include you in our CONTRIBUTORS.md (and let me know what name you want me to use)

**Comment by phoenix1796** [comment]
Yea , it'd be awesome @anishathalye :smile: 
Please use the name : Abhishek Chopra
& github-id: phoenix1796
:+1:

**Comment by anishathalye** [comment]
done!

**Pull request closed without merging**
